import { NextPage } from 'next';
import { TitleBar } from '../../../components/navigation/TitleBar';

import { AppWrapper } from '../../../components/wrappers/AppWrapper';

const SettingsPage: NextPage = () => (
  <AppWrapper titleBar={<TitleBar title="User Settings" />}>
    <div>
      <ul>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
        <li>ScrollTest</li>
      </ul>
    </div>
  </AppWrapper>
);

export default SettingsPage;
