import { NextPage } from 'next';
import { TitleBar } from '../../../components/navigation/TitleBar';

import { AppWrapper } from '../../../components/wrappers/AppWrapper';
import { useT } from '../../../lib/i18n';

const SettingsPage: NextPage = () => {
  const t = useT();

  return (
    <AppWrapper titleBar={<TitleBar title={t('menu.user.actions.settings') as string} />}>
      <div>
        <ul>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
          <li>ScrollTest</li>
        </ul>
      </div>
    </AppWrapper>
  );
};

export default SettingsPage;
